spring.application.name=api-gateway

spring.cloud.gateway.routes[0].id=questao-01
spring.cloud.gateway.routes[0].uri=lb://QUESTAO-01
spring.cloud.gateway.routes[0].predicates[0]=Path=/questao-01/**

spring.cloud.gateway.routes[1].id=questao-02
spring.cloud.gateway.routes[1].uri=lb://QUESTAO-02
spring.cloud.gateway.routes[1].predicates[0]=Path=/questao-02/**

spring.cloud.gateway.routes[2].id=questao-04
spring.cloud.gateway.routes[2].uri=lb://QUESTAO-04
spring.cloud.gateway.routes[2].predicates[0]=Path=/questao-04/**

spring.cloud.gateway.routes[3].id=questao-05
spring.cloud.gateway.routes[3].uri=lb://QUESTAO-05
spring.cloud.gateway.routes[3].predicates[0]=Path=/questao-05/**

spring.cloud.gateway.routes[4].id=questao-06
spring.cloud.gateway.routes[4].uri=lb://QUESTAO-06
spring.cloud.gateway.routes[4].predicates[0]=Path=/questao-06/**

spring.cloud.gateway.routes[5].id=questao-07
spring.cloud.gateway.routes[5].uri=lb://QUESTAO-07
spring.cloud.gateway.routes[5].predicates[0]=Path=/questao-07/**

eureka.instance.instance-id= ${spring.application.name}:${random.value}
eureka.client.service-url.defaultZone= http://localhost:8761/eureka
server.port=9999
