INSERT INTO TENIS(MODELO, MM_DROP, PESO, PRECO, ENTRESSOLA, MARCA_ID)
VALUES ('DYNABLAST 4', 8, 260, 350, 'FlyteFoam Blast', 1);
INSERT INTO TENIS(MODELO, MM_DROP, PESO, PRECO, ENTRESSOLA, MARCA_ID)
VALUES ('RACER NAIROBI', 8, 290, 260, 'EVA', 2);
INSERT INTO TENIS(MODELO, MM_DROP, PESO, PRECO, ENTRESSOLA, MARCA_ID)
VALUES ('ADIZERO SL', 10, 245, 550, 'Lightstrike Pro', 3);
INSERT INTO TENIS(MODELO, MM_DROP, PESO, PRECO, ENTRESSOLA, MARCA_ID)
VALUES ('PEGASUS 40', 10, 286, 455, 'REACT / AIR ZOOM', 4);