spring.application.name=api-gateway

spring.cloud.gateway.routes[0].id=pedido
spring.cloud.gateway.routes[0].uri=lb://PEDIDO-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/pedido/**

spring.cloud.gateway.routes[1].id=tenis
spring.cloud.gateway.routes[1].uri=lb://TENIS-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/tenis/**

spring.cloud.gateway.routes[2].id=marca
spring.cloud.gateway.routes[2].uri=lb://MARCA-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/marca/**

eureka.client.service-url.defaultUrl=http://localhost:8761/eureka
server.port=9999
