app.myport=${PORT:0}
server.port=${app.myport}

spring.main.allow-bean-definition-overriding=true

spring.application.name=marca-service

spring.datasource.url=jdbc:h2:mem:projetoDeBloco
spring.datasource.username=sa
spring.datasource.password=123123
spring.datasource.driver-class-name=org.h2.Driver

spring.h2.console.enabled=true

spring.jpa.show-sql=true
spring.jpa.database-plataform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true

eureka.instance.instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}