INSERT INTO MARCAS(NOME, PAIS, EMAIL, FUNDACAO)
VALUES ( 'ASICS', 'Japão', 'suporte@asics.com.br', '1949-09-01' );
INSERT INTO MARCAS(NOME, PAIS, EMAIL, FUNDACAO)
VALUES ( 'FILA', 'Itália', 'suporte@fila.com.br', '1911-01-01' );
INSERT INTO MARCAS(NOME, PAIS, EMAIL, FUNDACAO)
VALUES ( 'ADIDAS', 'Alemanha', 'suporte@adidas.com.br', '1949-08-18' );
INSERT INTO MARCAS(NOME, PAIS, EMAIL, FUNDACAO)
VALUES ( 'NIKE', 'EUA', 'suporte@nike.com.br', '1964-01-25' );

INSERT INTO TENIS(MODELO, MM_DROP, PESO, ENTRESSOLA, MARCA_ID)
VALUES ('DYNABLAST 4', 8, 260, 'FlyteFoam Blast', 1);
INSERT INTO TENIS(MODELO, MM_DROP, PESO, ENTRESSOLA, MARCA_ID)
VALUES ('RACER NAIROBI', 8, 290, 'EVA', 2);
INSERT INTO TENIS(MODELO, MM_DROP, PESO, ENTRESSOLA, MARCA_ID)
VALUES ('ADIZERO SL', 10, 245, 'Lightstrike Pro', 3);
INSERT INTO TENIS(MODELO, MM_DROP, PESO, ENTRESSOLA, MARCA_ID)
VALUES ('PEGASUS 40', 10, 286, 'REACT / AIR ZOOM', 4);

