name: CI Pipeline - AT Questão 11

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package --file "Microsserviços e DevOps com Spring Boot e Spring Cloud [24E3_3]/AT/questao-11/pom.xml"

      - name: Run Tests
        run: mvn test --file "Microsserviços e DevOps com Spring Boot e Spring Cloud [24E3_3]/AT/questao-11/pom.xml"